version: "3.1"

services:
  slack-bot:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    environment:
      - DATADOG_API_KEY
      - DATADOT_APP_KEY
      - NEWRELIC_TEAM_ID
      - NEWRELIC_LOGIN_EMAIL
      - NEWRELIC_LOGIN_PASS
      - ROLLBAR_WRITE_ACCESS_TOKEN
      - ROLLBAR_READ_ACCESS_TOKEN
    volumes:
      - ./:/go/src/app
    ports:
      - 3000:3000
